### PR TITLE
feat: migrate to biome

### LINKED ISSUE #332: Migrate off TSLint
```
$ npm run tslint

> @azure/oad@0.10.8 tslint
> tslint --project tsconfig.json "./src/**/*.ts"

The 'no-unnecessary-initializer' rule threw an error in '/home/mharder/openapi-diff-mh/src/lib/util/utils.ts':
TypeError: DeprecationError: 'originalKeywordKind' has been deprecated since v5.0.0 and can no longer be used. Use 'identifierToKeywordKind(identifier)' instead.
    at /home/mharder/openapi-diff-mh/node_modules/typescript/lib/typescript.js:174085:13
    at IdentifierObject.<anonymous> (/home/mharder/openapi-diff-mh/node_modules/typescript/lib/typescript.js:174115:7)
    at isUndefined (/home/mharder/openapi-diff-mh/node_modules/tslint/lib/rules/noUnnecessaryInitializerRule.js:106:14)
    at checkInitializer (/home/mharder/openapi-diff-mh/node_modules/tslint/lib/rules/noUnnecessaryInitializerRule.js:83:13)
    at cb (/home/mharder/openapi-diff-mh/node_modules/tslint/lib/rules/noUnnecessaryInitializerRule.js:60:21)
    at visitNodes (/home/mharder/openapi-diff-mh/node_modules/typescript/lib/typescript.js:28321:24)
    at forEachChildInVariableDeclarationList (/home/mharder/openapi-diff-mh/node_modules/typescript/lib/typescript.js:28970:18)
    at Object.forEachChild (/home/mharder/openapi-diff-mh/node_modules/typescript/lib/typescript.js:28406:37)
    at cb (/home/mharder/openapi-diff-mh/node_modules/tslint/lib/rules/noUnnecessaryInitializerRule.js:80:12)
    at visitNode2 (/home/mharder/openapi-diff-mh/node_modules/typescript/lib/typescript.js:28313:20)
```

I think we need to migrate off `tslint`, it's no longer being updated.

### PR DESCRIPTION
**Pull request by afonsojramos**
Fixes #332 by migrating to biome (which also allows for the replacement of prettier).

I was working on this prior to #335, so sorry @konrad-jamrozik for opening this after your PR, but I believe that moving to biome is more beneficial than moving to eslint. Granted, biome is not as battle tested, but it serves the purpose this project needs way better than eslint in my opinion. The performance benefits are just a plus.

### CODE REVIEW

**Comment by konrad-jamrozik** [comment]
@afonsojramos can you clarify why you are interested in this repository at all? What is your use case?

**Review by konrad-jamrozik — CHANGES_REQUESTED** [review]
@afonsojramos can you clarify why you are interested in this repository at all? What is your use case?

**Comment by konrad-jamrozik** [comment]
@afonsojramos sorry, but our team has standardized on `eslint` across our entire toolchain. In the future, I recommend for you to open an issue in this repo to discuss such bigger changes to avoid rework. Thanks!

**Comment by afonsojramos** [comment]
No worries, standards supersede all! Might still be something to consider even if just for the formatting perf vs prettier though!

> @afonsojramos can you clarify why you are interested in this repository at all? What is your use case?

Was investigating all of the openapi diffing tools out there and enjoyed seeing some activity on this one! In the end I found one that better fits our needs, but still found it very useful! Keep up the good job!

**Comment by konrad-jamrozik** [comment]
@afonsojramos thank you! Can you share the other diffing tools you looked at and which one you chose?

**Comment by afonsojramos** [comment]
Yeah, sure!

Seems like the ones that are being most used at the moment are: 
1. https://github.com/Tufin/oasdiff
2. https://github.com/pb33f/openapi-changes
3. https://github.com/OpenAPITools/openapi-diff
4. This one

Key features that we were looking for, but that were not present in all are:
1. Full OpenAPI 3.1 support
2. AsyncAPI support
3. Circular references support
4. `npm` support

As such, and due to the specific needs that we had, we ended up going with @udamir's https://github.com/udamir/api-smart-diff. It is built in a beautifully scalable way, full TS and in a very maintainable state.

So, if the star wasn't enough, thanks @udamir for that project! Hopefully I'll get to contribute to it in the future 🚀

**Pull request closed without merging**
